config/routes.rb
Rails.application.routes.draw do

 
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  root"home#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :albums
  
  get 'tags/:tag', to: 'albums#index', as: :tag

  # Defines the root path route ("/")
 
end

app/models/album.rb
 class Album < ApplicationRecord
    has_one_attached :cover_image
    has_many_attached :images
    belongs_to :user
    has_and_belongs_to_many :tags

    
    def tag_list
        tags.map(&:name).join(', ')
    end
    
      def tag_list=(names)
          self.tags = names.split(',').map do |n|
          Tag.where(name: n.strip).first_or_create!
        end
      end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
class Tag < ApplicationRecord
     has_and_belongs_to_many :albums     
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :albums
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    
    @albums = current_user.albums.where(published: true)
    @q = @albums.ransack(params[:q])
    @albums = @q.result(:distinct=>true)
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def create
    @album = current_user.albums.new(album_params)
    if @album.save
      redirect_to @album
       UserMailer.with(user: current_user).welcome_email.deliver_now
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
      @album = Album.find(params[:id])
  end

  def update 
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to @album
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    if @album.destroy
      UserMailer.with(user: current_user).destroy_mail.deliver_now
    end  
    redirect_to root_path, status: :see_other
  end

  private

  def album_params
    params.require(:album).permit(:title, :description, :cover_image, :published, :tag_list, images: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, address_attributes: [:country, :state, :city, :area, :postal_code]])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
    def index
      @q = Album.where(published: true).ransack(params[:q])
      @albums = @q.result
    end
  

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  
   #before_action :configure_sign_in_params, only: [:create]

  # def create
  #   super do |resource|
  #     BackgroundWorker.trigger(resource)
  #   end
  # end
  
  #<%= render "devise/shared/links" %>
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_footer.html.erb
<footer class="text-center text-white w-100">
  <!-- Grid container -->
  <div class="container pt-4">
    <section class="mb-4">
    
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center text-center1 text-dark p-3 text-decoration-none">
    © 2022 Copyright:
   <%= link_to "lets_play.com",albums_path, class: 'text-decoration-none'%>
  </div>
  <!-- Copyright -->
</footer>

app/views/albums/_form.html.erb
<%= form_with model: @album do |form| %>
   <div>
     <b><%= form.label :Name %><br></b>
     <%= form.text_field :title, class: 'form-control'%>
    </div>

    <div>
     <b><%= form.label :Description %><br></b>
     <%= form.text_field :description, class: 'form-control' %>
   </div>

  <div>
   <b><%= form.label :Media %><br></b>
   <%= form.file_field :cover_image, class: 'form-control' %>
  </div><br>

 <div>
   <b><%= form.label :Files%><br></b>
   <%= form.file_field :images , multiple:true, class: 'form-control'  %>
  </div><br> 

  <div>
   <b><%= form.label :Published%><br></b>
   <%= form.check_box :published %>
 </div><br>

 <div>
   <b><%= form.label :Tags%><br></b>
   <%= form.text_field :tag_list, class: 'form-control'  %>
 </div>

   <div>
    <br> <%= form.submit  %>
  </div>
<% end %>

app/views/albums/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light mt-3">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item ">
        <div class="m-2">
        <h2><b><%= link_to "Lets play" , root_path, class: "text-danger text-decoration-none" %></b></h2>
        </div>  
        </li>
        
        <li class="nav-item m-2">
            <% if user_signed_in?%>
              <%= link_to "New Album" , new_album_path, class: "text-decoration-none btn btn-success text-default" %> 
            <%end%>
        </li>

        <li class="nav-item m-2  ">
          <% if user_signed_in?%>
            <li class="nav-link text-default" href="/albums" ><%= link_to "LogOut", destroy_user_session_path, class: "text-decoration-none btn btn-danger text-default", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"                                   
                   }  %></li>
            <%else%>
              <%= link_to "login" , new_user_session_path, class: "text-decoration-none btn btn-success text-default" %>
          <%end%>
        </li>

        <li class="nav-item m-2">
          <% if user_signed_in?%>
            <%= link_to "MY Albums" , albums_path, class: "text-decoration-none btn btn-success text-default" %> 
          <%end%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/albums/edit.html.erb
 
 <%= render "nav" %>
       <div class="container">
              <div class="d-flex justify-content-center">
                 <%= render "form"  %>
                </div>
       </div>
<%= render "footer" %>

app/views/albums/index.html.erb
<%= render "nav" %>

<div class="mt-4 text-center "> 
  <%= search_form_for @q do |f| %>    
      <%= f.text_field :tags_name_cont, type: "search", class: "w-25" %>
      <%= f.submit class: "btn btn-primary"  %>    
  <% end %>
</div>
<div class="container mt-5 ">
  <div class="row row1">  
    <% @albums.each do |album| %>    
      <div class="col col-md-4 mt-3 ">
        <%= link_to album, class: "text-decoration-none" do %>
            <div class="card card1 text-black ">
              <%= image_tag (album.cover_image) if album.cover_image.attached?%>
              <div class="card-body row">
              <div class="col">
                <h5 class="card-title text-decoration-none ">
                  <h5>Title:</h5>
                  <%= album.title%>  
                  <h5>Tags:</h5>
                  <%= album.tag_list %>
                </h5>
              </div>
              </div>
            </div>
        <% end %>

          
          <%= link_to "Destroy", album_path(album.id), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
          }, class: 'btn btn-danger' %>
          <%=link_to "Edit" , edit_album_path(album), class: 'btn btn-secondary' %>
                                      
      </div>
    <% end %>
  </div>
</div>

<%= render "footer" %>

app/views/albums/new.html.erb
  <%= render "nav" %>
<div class="w-100 ">
<div class="w-25  mx-auto rounded border p-5">
<%= render "form" %>
</div>
</div>
<%= render "footer" %>

app/views/albums/show.html.erb
 <%= render "nav"   %>
<h1 class="mt-3 text-primary text-center">  Enjoy the music </h1>  
<% @album.images.each do |attachment|%>
  <div class="mt-2">
    <% if attachment.image? %>
        <%= image_tag (attachment), class: 'image' %>
      <% elsif attachment.audio? %>
        <audio controls>
        <source src="<%= rails_blob_url(attachment)%>" type="<%= attachment.content_type %>">
        </audio>
      <% elsif attachment.vedio? %>
        <vedio controls>
          <source src="<%= rails_blob_url(attachment)%>" type="<%= attachment.content_type %>">
        </vedio> 
  </div>
  <%end%>
<%end%><br>
 <div class="me-2">
    <%if current_user.present? && (current_user.id == @album.user_id)%>
              <%= link_to "Destroy", album_path(@album), data: {
                                  turbo_method: :delete,
                                  turbo_confirm: "Are you sure?"
                                }, class: 'btn btn-danger m-2'%> 
              <%=link_to "Edit" , edit_album_path(@album), class: 'btn btn-secondary me-2' %>                
      <%end%>
 </div>
 <%= render "footer" %>

app/views/home/index.html.erb
<%= render "albums/nav" %>
<div class="mt-4 text-center "> 
  <%= search_form_for @q do |f| %>    
      <%= f.text_field :tags_name_cont, type: "search", class: "w-25" %>
      <%= f.submit class: "btn btn-primary"  %>    
  <% end %>
</div>
<div class="container mt-5 ">
    <div class="row">  
        <% @albums.each do |album| %>    
            <div class="col-md-4 mt-3 ">
            <%= link_to album, class: "text-decoration-none" do %>
                <div class="card card1 text-black ">
                  <%= image_tag (album.cover_image) if album.cover_image.attached?%>
                  <div class="card-body row">
                  <div class="col">
                    <h5 class="card-title text-decoration-none ">
                      <h5>Title:</h5>
                      <%= album.title%>  
                      <h5>Tags:</h5>
                      <%= album.tag_list %>
                    </h5>
                  </div>
                  </div>
                </div>
            <% end %>
            </div>   
        <% end %>
    </div>
</div>
<%= render "albums/footer", class: 'mt-5'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Galleryapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>